"use client";
import {useEffect,useState} from "react"; import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts"; import {addDays,cycleDay,predictNext} from "@/lib/cycle";
type P={startDate:string,endDate?:string}; type S={date:string,symptoms:string[],mood:string};
export default function DashboardClient(){const [d,setD]=useState<any>(null);
useEffect(()=>{fetch("/api/data").then(r=>r.json()).then(setD)},[]);
if(!d)return <div className="page container">Loading your dashboard...</div>;
const periods:P[]=d.periods||[], last=periods[0], cycle=Number(d.user?.cycleLength||28), next=last?predictNext(new Date(last.startDate),cycle):null;
const chart=periods.slice(0,6).reverse().map((p,i)=>({name:`C${i+1}`,length:i<periods.length-1?Math.round((new Date(periods.slice(0,6).reverse()[i+1].startDate).getTime()-new Date(p.startDate).getTime())/86400000):cycle}));
return <main className="page"><div className="container"><div className="row" style={{justifyContent:"space-between",marginBottom:20}}><div><h1>Hi, {d.user?.name?.split(" ")[0]}</h1><p className="muted">A simple view of your cycle.</p></div><span className="badge">{last?`Cycle day ${cycleDay(new Date(last.startDate))}`:"Log your first period"}</span></div>
<div className="grid grid4"><div className="card"><div className="small muted">Last period</div><div className="stat">{last?new Date(last.startDate).toLocaleDateString():"—"}</div></div><div className="card"><div className="small muted">Cycle length</div><div className="stat">{cycle}d</div></div><div className="card"><div className="small muted">Next estimated period</div><div className="stat">{next?next.toLocaleDateString():"—"}</div></div><div className="card"><div className="small muted">Entries</div><div className="stat">{periods.length+(d.symptoms||[]).length}</div></div></div>
<div className="grid grid2" style={{marginTop:16}}><div className="card"><h2>Cycle history</h2>{chart.length?<ResponsiveContainer width="100%" height={250}><LineChart data={chart}><XAxis dataKey="name"/><YAxis/><Tooltip/><Line type="monotone" dataKey="length" stroke="var(--plum)" strokeWidth={3}/></LineChart></ResponsiveContainer>:<p className="muted">Log at least two periods to see your cycle trend.</p>}</div><div className="card"><h2>Recent symptoms</h2>{(d.symptoms||[]).slice(0,5).map((s:S,i)=><div key={i} style={{padding:"10px 0",borderBottom:"1px solid var(--line)"}}><b>{new Date(s.date).toLocaleDateString()}</b><div className="small muted">{s.symptoms?.join(", ")||"No symptoms listed"} {s.mood&&` • ${s.mood}`}</div></div>)||<p className="muted">No symptom entries yet.</p>}</div></div>
</div></main>}
